---
# tasks file for swygue-redhat-subscription

- name: ensure subscription-manager is installed
  tags: [checks, register, unregister, repos, consumer_ca, katello_ca]
  block:
    - name: check if subscription-manager is installed
      command: yum list installed subscription-manager
      args:
        warn: no
      changed_when: False
  rescue:
    - name: report when subscription-manager isn't stalled
      debug:
        msg: 'Cannot continue because subscription-manager was not found on the system.'

- name: check if system is registered
  command: subscription-manager refresh
  register: is_system_registered
  failed_when: False
  changed_when: False
  tags: [checks, register, unregister, repos, consumer_ca, katello_ca]

- name: declare fact system_registered true if status is registered
  set_fact:
    system_registered: "{{ true if is_system_registered.rc==0 else false }}"
    system_registered_msg: "{{ 'registered' if is_system_registered.rc==0 else 'not registered' }}"
  tags: [ register, unregister, repos, consumer_ca, katello_ca]

- name: declare fact remove_system_registration if rhsm_unregister is set
  set_fact:
    remove_system_registration: "{{ true if rhsm_unregister else false }}"
  tags: [ register, unregister, repos, consumer_ca, katello_ca]

- name: set fact use_system_identity when rhsm_identity is defined
  set_fact:
    use_system_identity: "{{ false if rhsm_identity == '' else true }}"
  tags: [register]

- name: set fact use_activation_key when rhsm_activationkey is defined
  set_fact:
    use_activation_key: "{{ false if rhsm_activationkey == '' else true }}"
  tags: [register]

- name: check system if system is in the right ORG
  include_tasks: check_org.yml
  when: (system_registered == true and rhsm_org_id is defined) and (rhsm_org_id != "")
  tags: [register]

- name: check system if system consuming the right content view
  include_tasks: check_cv.yml
  when: (system_registered == true and rhsm_content_view is defined) and (rhsm_content_view | length > 0)
  tags: [register]

- name: check system if system is registered to the correct RHSM host
  include_tasks: check_rhsm_hostname.yml
  when: system_registered == true and rhsm_hostname != ""
  tags: [register]

- name: check system registration status
  shell: >
      subscription-manager status | awk '/Overall Status:/ {print $3}'
  failed_when: False
  changed_when: False
  register: system_rhsm_status
  tags: [ register, unregister, repos, consumer_ca, katello_ca]

## need to find a better way to fix registration when status is not Current
#- name: set fix_registration to true if subscription-manager status is not current
#  set_fact:
#    fix_registration: true
#  when: system_rhsm_status.stdout != 'Current'

- name: set rhsm_fix_registration to true if fix_registration is defined
  set_fact:
    rhsm_fix_registration: "{{ true if fix_registration == true else false }}"
  tags: [ register, unregister, repos, consumer_ca, katello_ca]

- name: display some keys facts about system registration
  debug:
    msg:
      - "use_activation_key = {{ use_activation_key }}"
      - "use_system_identity = {{ use_system_identity }}"
      - "system_registered = {{ system_registered }}"
      - "rhsm_fix_registration = {{ rhsm_fix_registration }}"
      - "org_id_is_correct = {{ org_id_is_correct }}"
      - "contentview_is_correct = {{ contentview_is_correct }}"
      - "rhsm_host_is_correct = {{ rhsm_host_is_correct }}"
      - "fix_registration = {{ fix_registration }}"
      - "The system is {{ system_registered_msg }}."
  tags: [register,consumer_ca]


- name: UNREGISTER|remove system rhsm registration if subscription is not current or rhsm ORG id does not match the systems current registered ORG id
  include_tasks: unregister.yml
  when: ( (remove_system_registration|bool ) and
          (system_registered|bool ) or
          ( rhsm_fix_registration|bool ))
  tags: [unregister]

- name: REGISTER|register system to RHSM or Satellite
  include_tasks: register.yml
  when: ( (system_registered != true) and
          (remove_system_registration != true) or
          (rhsm_fix_registration == true))
  tags: [register,consumer_ca]

- name: REPOS| enable system repositories
  include_tasks: repos.yml
  when: (system_registered|bool and not remove_system_registration|bool)
         or (rhsm_fix_registration|bool)
  tags: [register,repos]

