---
# TODO: Add task to update the ORG a update belong to before registering
#       Assuming host already exists.

- name: include check_katello_ca.yml
  include_tasks: check_katello_ca.yml
  tags: [register, katello_ca]

- name: clean out existing subscription certificate
  shell: subscription-manager clean
  register: rhsm_clean
  changed_when: False
  ignore_errors: yes
  tags: [register]

- name: declare rhsm server_url and rhsm base_url
  set_fact:
    server_url: "{{ rhsm_server_url }}"
    base_url: "{{ rhsm_base_url }}"
  when: rhsm_is_satellite|bool
  tags: [register]

- name: install the katello consumer rpm
  package:
    name: "http://{{ rhsm_hostname }}/pub/{{ rhsm_katello_ca_consumer_rpm }}"
    state: present
  when: katello_ca_installed|default(false)|bool == false and rhsm_is_satellite|bool
  tags: [register]

# This has not been tested againist Satellite
# Attempt to register system using an existing identity if defined
# undefine use_system_identity if registration fails
- name: Register system using rhsm_identity
  when: use_system_identity|bool and not use_activation_key|bool
  tags: [register]
  block:
    - name: Registering system {{ inventory_hostname }} with rhsm_identity
      redhat_subscription:
        state: present
        activationkey: "{{ rhsm_activationkey }}"
        server_hostname: "{{ server_url | default(omit) }}"
        rhsm_baseurl: "{{ base_url | default(omit) }}"
        org_id: "{{ rhsm_org_id }}"
        use_system_identity: "{{ rhsm_identity }}"
        syspurpose: "{{ system_purpose | default(omit) }}"
      register: is_registered_use_system_identity
  rescue:
      - name: set fact use_system_identity when rhsm_identity is defined
        set_fact:
          use_system_identity: false

- name: Register {{ inventory_hostname }} to RHSM using activation key
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_activationkey }}"
    server_hostname: "{{ server_url | default(omit) }}"
    rhsm_baseurl: "{{ base_url | default(omit) }}"
    org_id: "{{ rhsm_org_id }}"
    force_register: yes
    syspurpose: "{{ system_purpose | default(omit) }}"
  register: is_registered_actkey
  when: use_activation_key|bool and not use_system_identity|bool
  tags: [register]
        
- name: Register {{ inventory_hostname }} system using rhsm_user and rhsm_password
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    server_hostname: "{{ server_url | default(omit) }}"
    rhsm_baseurl: "{{ base_url | default(omit) }}"
    auto_attach: true
    force_register: yes
    org_id: "{{ rhsm_org_id|default(null) }}"
    syspurpose: "{{ system_purpose | default(omit) }}"
  register: is_registered_rhsm_user
  when: not use_system_identity|bool and not use_activation_key|bool
  tags: [register]

- name: refresh subscriptions
  shell: subscription-manager refresh
  register: rhsm_refresh
  changed_when: False
  when: is_registered_rhsm_user.changed
  tags: [register]

- name: REPOS| enable system repositories
  include_tasks: repos.yml
  when: is_registered_rhsm_user.changed or is_registered_use_system_identity.changed or is_registered_actkey.changed
  tags: [register,repos]
